# This file defines the items one might find in the game.
# It is used by 'build' to generate two files:
#     build/item_globals.ink - contains the VAR specifications for all of the items
#     build/item_globals.js - defines the json global variable 'storyItems'
#
# Items are stored in the [items] block.  The core name used for the ink variable
# and the HTML entities is "name" from [item.{name}].  This name should be simple
# lowercase letters (a-z) and the underscore character for compatibility with
# TOML, JSON, Ink and HTML ids.
#
# Required item keys:
# name = "Short name"   - simple item screen name for lists, etc
# description = "Item description"  - a longer text block describing the item
#
# Optional item keys:
# url = "items/tattoo.png"   - local URL to an image of the item
#

[items]

[items.tattooed]
name = "Tattoo"
description = "A tattoo, laser burnt into your arm."
url = "items/tattoo.png"

[items.padded_cell_key]
name = "Digital card key"
description = "A standard magnetic card swipe key."
url = "items/keycard.png"

[items.lcd_display]
name = "LCD display board"
description = "A flat panel display module."
url = "items/lcd_panel.png"

#
# States
#
# States define a collection of entities that represent
# things that are represented as integer counts.  Things
# like "health" or "gold", etc are of this ilk.  Like
# items, the ink variable is defined using tha name [states.{name}]
#
# Required state keys:
# name = "Short name"   - simple item screen name for the value
# default = X   - the default value used in the .ink VAR value
# hide = Y   - specify a condition where the state is to be hidden in the GUI
#            - 0=always show, 1=hide, 2=hide if value is 0
#
# Optional item keys:
# hide_variable = "varname"   - if specified, this variable value is to be
#                             - used in the evaluation of 'hide' instead of
#                             - the state value variable.
# percent = 1   - if present, the value is interpreted as a "percentage" for display
#
[states]

[states.exo_power]
name = "ZXT Mark V power"
default = 100
hide = 2
hide_variable = "tattooed"
percent = 1
