# This file defines the items one might find in the game.
# It is used by 'build' to generate two files:
#     build/item_globals.ink - contains the VAR specifications for all of the items
#     build/item_globals.js - defines the json global variable 'storyItems'
#
# Items are stored in the [items] block.  The core name used for the ink variable
# and the HTML entities is "name" from [item.{name}].  This name should be simple
# lowercase letters (a-z) and the underscore character for compatibility with
# TOML, JSON, Ink and HTML ids.
#
# Required item keys:
# name = "Short name"   - simple item screen name for lists, etc
# description = "Item description"  - a longer text block describing the item
#
# Optional item keys:
# url = "items/tattoo.png"   - local URL to an image of the item
# hide_variable = "varname"  - name of a variable that will hide the item is the variable is non-zero
# code = "varname"           - the name of a variable with a keycode value
# symbol = "1"               - if 'symbol' is present, then the code is symbols, not numbers
#

[items]

[items.tattooed]
name = "Tattoo"
description = "A tattoo, laser burnt into your arm."
url = "items/tattoo.png"

[items.padded_cell_key]
name = "Magnetic card key"
description = "A standard magnetic card swipe key."
url = "items/keycard.png"

[items.insane_laura]
name = "Mechanical owl"
description = "A marvel of science? There seems to be an entity inside, but one might question its sanity."
url = "items/owl.png"

[items.garden_door_key]
name = "A large iron key"
description = "This looks like a gate key."
hide_variable = "temple_found"

[items.crutch]
name = "Crutch"
description = "A rough and worn crutch: GLYPH0"

[items.anthropoid_gear]
name = "Anthropoid gear"
description = "A tempered gear GLYPH8 harvested from an anthropoid receptacle."

# Note the embedded table is generated using the 'plate.py' file
[items.sunbeam_plate]
name = "Sunbeam plate"
description = "A silver plate polished to a mirror shine.  A grid of glyphs decorates the center:<br><table style='width:100%'><table style='width:100%'><tr><th>GLYPH7</th><th>GLYPH0</th><th>GLYPH8</th><th>GLYPH8</th><th>GLYPH8</th></tr><tr><th>GLYPH2</th><th>GLYPH3</th><th>GLYPH5</th><th>GLYPH7</th><th>GLYPH3</th></tr><tr><th>GLYPH4</th><th>GLYPH2</th><th>GLYPH5</th><th>GLYPH0</th><th>GLYPH5</th></tr><tr><th>GLYPH5</th><th>GLYPH5</th><th>GLYPH6</th><th>GLYPH7</th><th>GLYPH9</th></tr><tr><th>GLYPH2</th><th>GLYPH3</th><th>GLYPH1</th><th>GLYPH8</th><th>GLYPH7</th></tr></table>"

[items.melampus_key]
name = "Melampus door code"
description = "The digital door code for Melampus' office."
hide_variable = "melampus_list"
code = "code_melampus"

[items.helped_beggar]
name = "Cloth swatch"
description = "A Time Corrections Agency badge only issued to Agency personnel."
url = "items/agency_badge.png"

[items.melampus_list]
name = "Melampus item list"
description = "- Oscillator<br>- Gold wiring<br>- LCD display<br>- Simple battery"
hide_variable = "antivirus"

[items.antivirus]
name = "Antivirus USB key"
description = "Melampus developed USB key containing custom antivirus software that can be used to 'decode' Laura."
url = "items/antivirus.png"

[items.oscillator]
name = "Oscillator"
description = "A finely tuned crystal oscillator."
url = "items/oscillator.png"

[items.lcd_display]
name = "LCD display board"
description = "A flat panel display module."
url = "items/lcd_panel.png"

[items.gold_wiring]
name = "Gold wire"
description = "A spool of gold wire."
url = "items/gold_wiring.png"

[items.simple_battery]
name = "Battery"
description = "A simple Li-W battery."
url = "items/simple_battery.png"

[items.crypto_unit]
name = "Quantum Cryptograph"
description = "Capable of decoding the most complex cyphers with relative ease (and enough power)."

[items.quad_shield]
name = "Quadiken Shield"
description = "Shield unit that protects against a Quadiken (electromagnetic) weapon."

[items.fava_beans]
name = "Fava beans"
description = "A simple bowl of fava beans."
url = "items/fava.png"

[items.door_to_oracle_code]
name = "Room 237 keycode"
description = "A digital lock keycode. Provides access to the Oracle at the Temple of Apollo."
code = "code_apollo_foyer"
symbol = "1"

[items.apollo_backroom_keycode]
name = "Apollo gate code"
description = "A digital lock core for Temple of Apollo entry gate."
code = "code_apollo_backroom"
symbol = "1"

[items.novel]
name = "Novel"
description = "Gravity's Rainbow by Thomas Pynchon."
url = "items/novel.jpg"

[items.dummies_book]
name = "Dummies Book"
description = "Space-Time Portals for Dummies by Professor Jordan Hastings."
url = "items/st_dummies.png"

[items.soulgem_empty]
name = "Empty Soul Gem"
description = "An empty soul gem pendant."
url = "items/soul_empty.png"

[items.soulgem_full]
name = "Full Soul Gem"
description = "A full soul gem pendant."
url = "items/soul_full.png"

[items.stun_orb]
name = "Stun Orb"
description = "A Robinson Psychosis 534 Stun Orb. Sometimes in combat you just need a little extra boost.  The stun orb will slow your attacker just a little bit, without disrupting your attack."

[items.combat_training]
name = "Mark II combat training"
description = "The combat training program from a Mark II receptacle.  It improves reflexes and targeting in combat situations."

[items.computer_room_key]
name = "Contactless keycard"
description = "Computer room special access card."
url = "items/computer_room_key.png"

[items.hypermarket_id]
name = "HyperMarket ID"
description = "An ID badge that identifies you as 'James Smith'."
url = "items/james_id.png"

[items.item_shorts]
name = "Shorts"
description = "While those may have been in vogue in Spain, say 1499, one has to question this choice."
url = "items/shorts.png"

[items.item_poloshirt]
name = "Polo shirt"
description = "Black poloshirt with an embroidered owl."
url = "items/poloshirt.png"

[items.item_poloshirt_inquisition]
name = "Polo shirt"
description = "Black poloshirt with the Inquisition logo embroidered on it."
url = "items/poloshirt.png"

[items.item_poloshirt_plain]
name = "Polo shirt"
description = "Plain black poloshirt."
url = "items/poloshirt.png"

[items.item_sandals]
name = "Sandals"
description = "There’s only one being that could pull off those sandals… and it isn’t you. Besides, open-toed shoes on a male?"
url = "items/sandals.png"

[items.inquisition_leader_badge]
name = "Inquisition Badge"
description = "A badge marking you as being a high-level Inquisition leader."
url = "items/inq_badge.png"

[items.wafer_chip]
name = "Computer wafer chip"
description = "A circular computer chip."
url = "items/wafer.png"

[items.crm114_key]
name = "CRM114 key"
description = "Allows the CRM114 to be changed to other settings."

#
# States
#
# States define a collection of entities that represent
# things that are represented as integer counts.  Things
# like "health" or "gold", etc are of this ilk.  Like
# items, the ink variable is defined using tha name [states.{name}]
#
# Required state keys:
# name = "Short name"   - simple item screen name for the value
# default = X   - the default value used in the .ink VAR value
# hide = Y   - specify a condition where the state is to be hidden in the GUI
#            - 0=always show, 1=hide, 2=hide if value is 0
#
# Optional item keys:
# hide_variable = "varname"   - if specified, this variable value is to be
#                             - used in the evaluation of 'hide' instead of
#                             - the state value variable.
# percent = 1   - if present, the value is interpreted as a "percentage" for display
#
[states]

[states.exo_power]
name = "Mark V power"
default = 100
hide = 2
hide_variable = "tattooed"
percent = 1

[states.cash]
name = "Drachm"
default = 10
hide = 2
hide_variable = "tattooed"
