# This file defines the items one might find in the game.
# It is used by 'build' to generate two files:
#     build/item_globals.ink - contains the VAR specifications for all of the items
#     build/item_globals.js - defines the json global variable 'storyItems'
#
# Items are stored in the [items] block.  The core name used for the ink variable
# and the HTML entities is "name" from [item.{name}].  This name should be simple
# lowercase letters (a-z) and the underscore character for compatibility with
# TOML, JSON, Ink and HTML ids.
#
# Required item keys:
# name = "Short name"   - simple item screen name for lists, etc
# description = "Item description"  - a longer text block describing the item
#
# Optional item keys:
# url = "items/tattoo.png"   - local URL to an image of the item
# hide_variable = "varname"  - name of a variable that will hide the item is the variable is non-zero
# code = "varname"           - the name of a variable with a keycode value
# symbol = "1"               - if 'symbol' is present, then the code is symbols, not numbers
#

[items]

[items.tattooed]
name = "Tattoo"
description = "A tattoo, laser burnt into your arm."
url = "items/tattoo.png"

[items.padded_cell_key]
name = "Magnetic card key"
description = "A standard magnetic card swipe key."
url = "items/keycard.png"

[items.insane_laura]
name = "Mechanical owl"
description = "A marvel of science? There seems to be an entity inside, but one might question its sanity."
url = "items/owl.png"

[items.garden_door_key]
name = "A large iron key"
description = "This looks like a gate key."
hide_variable = "temple_found"

[items.crutch]
name = "Crutch"
description = "A rough and worn crutch."

[items.anthropoid_gear]
name = "Anthropoid gear"
description = "A tempered gear harvested from an anthropoid receptacle."

[items.sunbeam_plate]
name = "Sunbeam plate"
description = "An old man with a crutch walks away from a pomegranate tree against a night sky. Right of the elderly man, a bearded man holds a set of scales and points to a complex mechanical apparatus to the right."

[items.melampus_key]
name = "Melampus door code"
description = "The digital door code for Melampus' office."
hide_variable = "melampus_list"
code = "code_melampus"

[items.melampus_list]
name = "Melampus item list"
description = "- Oscillator<br>- Gold wiring<br>- LCD display<br>- Simple battery"
hide_variable = "antivirus"

[items.antivirus]
name = "Antivirus"
description = "Custom-developed USB key containing software needed to 'unlock' Laura."
url = "items/antivirus.png"

[items.oscillator]
name = "Oscillator"
description = "A finely tuned crystal oscillator."
url = "items/oscillator.jpg"

[items.lcd_display]
name = "LCD display board"
description = "A flat panel display module."
url = "items/lcd_panel.png"

[items.gold_wiring]
name = "Gold wire"
description = "A spool of gold wire."
url = "items/gold_wiring.jpg"

[items.simple_battery]
name = "Battery"
description = "A simple Li-W battery."
url = "items/simple_battery.png"

[items.crypto_unit]
name = "Quantum Cryptograph"
description = "Capable of decoding the most complex cyphers with relative ease (and enough power)."

[items.quad_shield]
name = "Quadiken Shield"
description = "Shield unit that protects against a Quadiken (electromagnetic) weapon."

[items.fava_beans]
name = "Fava beans"
description = "A simple bowl of fava beans."
url = "items/fava.png"

[items.door_to_oracle_code]
name = "Room 237 keycode"
description = "A digital lock keycode."
code = "code_apollo_foyer"
symbol = "1"

[items.apollo_backroom_keycode]
name = "Apollo backroom code"
description = "A digital lock keycode."
code = "code_apollo_backroom"
symbol = "1"

[items.novel]
name = "Novel"
description = "Gravity's Rainbow by Thomas Pynchon."
url = "items/novel.jpg"

[items.stun_orb]
name = "Stun Orb"
description = "A Robinson Psychosis 534 Stun Orb. Sometimes in combat you just need a little extra boost.  The stun orb will slow your attacker just a little bit, without disrupting your attack."

[items.combat_training]
name = "Mark II combat training"
description = "The combat training program from a Mark II receptacle.  It improves reflexes and targeting in combat situations."

[items.computer_room_key]
name = "Contactless keycard"
description = "Computer room special access card."
url = "items/computer_room_key.png"

[items.hypermarket_id]
name = "HyperMarket ID"
description = "An ID badge that identifies you as 'James'."

[items.item_shorts]
name = "Shorts"
description = "What are you?  5?  A whore?  A 5 year old whore? "
url = "items/shorts.png"

[items.item_poloshirt]
name = "Polo shirt"
description = "An ID badge that identifies you as 'James'."
url = "items/poloshirt.png"

[items.item_sandals]
name = "Sandals"
description = "There’s only one being that could pull off those sandals… and it isn’t you. What were you thinking?"
url = "items/sandals.png"

[items.inquisition_leader_badge]
name = "Inquisition Badge"
description = "A badge marking you as being a high-level Inquisition leader"
url = "items/inq_badge.png"

[items.wafer_chip]
name = "Computer wafer chip"
description = "A circular computer chip."
url = "items/wafer.png"

#
# States
#
# States define a collection of entities that represent
# things that are represented as integer counts.  Things
# like "health" or "gold", etc are of this ilk.  Like
# items, the ink variable is defined using tha name [states.{name}]
#
# Required state keys:
# name = "Short name"   - simple item screen name for the value
# default = X   - the default value used in the .ink VAR value
# hide = Y   - specify a condition where the state is to be hidden in the GUI
#            - 0=always show, 1=hide, 2=hide if value is 0
#
# Optional item keys:
# hide_variable = "varname"   - if specified, this variable value is to be
#                             - used in the evaluation of 'hide' instead of
#                             - the state value variable.
# percent = 1   - if present, the value is interpreted as a "percentage" for display
#
[states]

[states.exo_power]
name = "Mark V power"
default = 100
hide = 2
hide_variable = "tattooed"
percent = 1

[states.cash]
name = "Drachm"
default = 10
hide = 2
hide_variable = "tattooed"
